### ISSUE TITLE
Render Performance of DirectX Plugin in HoloLens

### ISSUE THREAD

**Issue by ritchielozada** [ritchielozada/UnityWithWebRTC#1]
Render performance of DirectX plugin in Unity to process and display graphics need significant improvement compared to a pure DirectX project.    A native DirectX implementation is able to achieve 30+ frames per second update while a plugin with Unity is less than 5 frames per second.

**Comment by phongcao** [comment]
Hi Ritchie, you may have a chat with Andrei about this issue since he seems to be able to improve the performance a lot now.

**Comment by ritchielozada** [comment]
Major performance improvement is to unify the WebRTC call into a common library using core WebRTC libraries instead of being bridged through Unity3D.
