### ISSUE TITLE
Question Server

### ISSUE THREAD

**Issue by StarBax89** [ritchielozada/UnityWithWebRTC#11]
Hi @ritchielozada ,

one question, where is the server from? Is it opensource?

Regards

**Comment by ritchielozada** [comment]
Hello,

The server .exe file was from https://github.com/webrtc-uwp/PeerCC which is a binary build/compile of the dev/test server https://webrtc.org/native-code/development.   The license grants are posted in https://webrtc.org/license/.

Ritchie

**Comment by StarBax89** [comment]
Thank you!
