### ISSUE TITLE
import Org.WebRtc.dll problem

### ISSUE THREAD

**Issue by pytel87** [ritchielozada/UnityWithWebRTC#5]
Hi,
I have problem with importing Org.WebRtc.dll into my project. 
Is there any other action needed, other then copy the file into project Asset folder?
Thank you.

**Comment by ritchielozada** [comment]
Org.WebRtc.dll is managed in Visual Studio through Nuget -- in Unity you would have to copy the DLL explicitly to a pre-defined plugins folder and set the properties to match for UWP/Windows Store, processor settings etc.

**Comment by ritchielozada** [comment]
Tested in clean setup - Org.WebRtc.dll and winmd are in plugin folder for Unity and Visual Studio Project can use Nuget.
