### ISSUE TITLE
Does it work well in hololens?

### ISSUE THREAD

**Issue by xuxu123** [ritchielozada/UnityWithWebRTC#8]
I have made it work with hololens. But the frame rate is very low, and the usage of CPU is very high. Is there any resolution to deal with this problem. Btw, it seems some "TODO" work in choose the video encoder. Does it use the Raw Data to communicate?

**Comment by ritchielozada** [comment]
It is the same experience I have with the HoloLens (V1 hardware and software platform), while the UWP application works, the framerate is very low with the image processing running on the limited CPU resource.

The WebRTC session is setup to use H264 video encoding on the network peer session, and the WebRTC UWP wrapper provides both H264 encoded frames, and decoded raw frames but I need to perform a YUV color fix to display properly on the Unity Quad on the native plugin side.

Note that even doing simple BitBlt on the image buffer used by the texture on the native plugin drops the framerate significantly on the Unity player runtime and the native plugin manipulating images.

To achieve a more acceptable framerate on the HoloLens, an alternative solution is to write a native UWP DirectX app that uses the WebRTC library and get the full available hardware resources for your application.   I am personally hoping an eventual hardware/system upgrade on the HoloLens or code access to the hardware video processor to offload the CPU improves the performance with Unity.

**Comment by xuxu123** [comment]
Thank you very much.
